// Copyright 2026 The KubeTraffic Authors.
// SPDX-License-Identifier: Apache-2.0
//
// Shared gRPC contract between the Go controller and the Java control plane.
// Regenerate with:
//   controller/hack/gen-proto.sh   (Go)
//   mvn generate-sources           (Java, via control-plane/pom.xml)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: kubetraffic/v1/route.proto

package kubetrafficv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteService_RegisterRoute_FullMethodName  = "/kubetraffic.v1.RouteService/RegisterRoute"
	RouteService_DeleteRoute_FullMethodName    = "/kubetraffic.v1.RouteService/DeleteRoute"
	RouteService_GetRouteConfig_FullMethodName = "/kubetraffic.v1.RouteService/GetRouteConfig"
)

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteServiceClient interface {
	// RegisterRoute idempotently upserts a route's desired spec and returns the
	// current effective configuration.
	RegisterRoute(ctx context.Context, in *RouteSpec, opts ...grpc.CallOption) (*RouteConfig, error)
	// DeleteRoute removes a route the controller no longer manages.
	DeleteRoute(ctx context.Context, in *RouteRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetRouteConfig polls the effective configuration. Used as a fallback when
	// the decision stream is unavailable.
	GetRouteConfig(ctx context.Context, in *RouteRef, opts ...grpc.CallOption) (*RouteConfig, error)
}

type routeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteServiceClient(cc grpc.ClientConnInterface) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) RegisterRoute(ctx context.Context, in *RouteSpec, opts ...grpc.CallOption) (*RouteConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteConfig)
	err := c.cc.Invoke(ctx, RouteService_RegisterRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) DeleteRoute(ctx context.Context, in *RouteRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RouteService_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) GetRouteConfig(ctx context.Context, in *RouteRef, opts ...grpc.CallOption) (*RouteConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteConfig)
	err := c.cc.Invoke(ctx, RouteService_GetRouteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServiceServer is the server API for RouteService service.
// All implementations must embed UnimplementedRouteServiceServer
// for forward compatibility.
type RouteServiceServer interface {
	// RegisterRoute idempotently upserts a route's desired spec and returns the
	// current effective configuration.
	RegisterRoute(context.Context, *RouteSpec) (*RouteConfig, error)
	// DeleteRoute removes a route the controller no longer manages.
	DeleteRoute(context.Context, *RouteRef) (*emptypb.Empty, error)
	// GetRouteConfig polls the effective configuration. Used as a fallback when
	// the decision stream is unavailable.
	GetRouteConfig(context.Context, *RouteRef) (*RouteConfig, error)
	mustEmbedUnimplementedRouteServiceServer()
}

// UnimplementedRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteServiceServer struct{}

func (UnimplementedRouteServiceServer) RegisterRoute(context.Context, *RouteSpec) (*RouteConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRoute not implemented")
}
func (UnimplementedRouteServiceServer) DeleteRoute(context.Context, *RouteRef) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedRouteServiceServer) GetRouteConfig(context.Context, *RouteRef) (*RouteConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRouteConfig not implemented")
}
func (UnimplementedRouteServiceServer) mustEmbedUnimplementedRouteServiceServer() {}
func (UnimplementedRouteServiceServer) testEmbeddedByValue()                      {}

// UnsafeRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServiceServer will
// result in compilation errors.
type UnsafeRouteServiceServer interface {
	mustEmbedUnimplementedRouteServiceServer()
}

func RegisterRouteServiceServer(s grpc.ServiceRegistrar, srv RouteServiceServer) {
	// If the following call pancis, it indicates UnimplementedRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteService_ServiceDesc, srv)
}

func _RouteService_RegisterRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).RegisterRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_RegisterRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).RegisterRoute(ctx, req.(*RouteSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).DeleteRoute(ctx, req.(*RouteRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_GetRouteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetRouteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_GetRouteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetRouteConfig(ctx, req.(*RouteRef))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteService_ServiceDesc is the grpc.ServiceDesc for RouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubetraffic.v1.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRoute",
			Handler:    _RouteService_RegisterRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _RouteService_DeleteRoute_Handler,
		},
		{
			MethodName: "GetRouteConfig",
			Handler:    _RouteService_GetRouteConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubetraffic/v1/route.proto",
}

const (
	DecisionService_StreamDecisions_FullMethodName = "/kubetraffic.v1.DecisionService/StreamDecisions"
)

// DecisionServiceClient is the client API for DecisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecisionServiceClient interface {
	// StreamDecisions pushes every effective-weight change the control plane
	// records, so controllers react without polling.
	StreamDecisions(ctx context.Context, in *WatchDecisionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Decision], error)
}

type decisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecisionServiceClient(cc grpc.ClientConnInterface) DecisionServiceClient {
	return &decisionServiceClient{cc}
}

func (c *decisionServiceClient) StreamDecisions(ctx context.Context, in *WatchDecisionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Decision], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecisionService_ServiceDesc.Streams[0], DecisionService_StreamDecisions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDecisionsRequest, Decision]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionService_StreamDecisionsClient = grpc.ServerStreamingClient[Decision]

// DecisionServiceServer is the server API for DecisionService service.
// All implementations must embed UnimplementedDecisionServiceServer
// for forward compatibility.
type DecisionServiceServer interface {
	// StreamDecisions pushes every effective-weight change the control plane
	// records, so controllers react without polling.
	StreamDecisions(*WatchDecisionsRequest, grpc.ServerStreamingServer[Decision]) error
	mustEmbedUnimplementedDecisionServiceServer()
}

// UnimplementedDecisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecisionServiceServer struct{}

func (UnimplementedDecisionServiceServer) StreamDecisions(*WatchDecisionsRequest, grpc.ServerStreamingServer[Decision]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDecisions not implemented")
}
func (UnimplementedDecisionServiceServer) mustEmbedUnimplementedDecisionServiceServer() {}
func (UnimplementedDecisionServiceServer) testEmbeddedByValue()                         {}

// UnsafeDecisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecisionServiceServer will
// result in compilation errors.
type UnsafeDecisionServiceServer interface {
	mustEmbedUnimplementedDecisionServiceServer()
}

func RegisterDecisionServiceServer(s grpc.ServiceRegistrar, srv DecisionServiceServer) {
	// If the following call pancis, it indicates UnimplementedDecisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecisionService_ServiceDesc, srv)
}

func _DecisionService_StreamDecisions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDecisionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecisionServiceServer).StreamDecisions(m, &grpc.GenericServerStream[WatchDecisionsRequest, Decision]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionService_StreamDecisionsServer = grpc.ServerStreamingServer[Decision]

// DecisionService_ServiceDesc is the grpc.ServiceDesc for DecisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubetraffic.v1.DecisionService",
	HandlerType: (*DecisionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDecisions",
			Handler:       _DecisionService_StreamDecisions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kubetraffic/v1/route.proto",
}
