apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: kubetraffic-demo
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
