---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetraffic-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traffic.kubetraffic.io
  resources:
  - trafficroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.kubetraffic.io
  resources:
  - trafficroutes/finalizers
  verbs:
  - update
- apiGroups:
  - traffic.kubetraffic.io
  resources:
  - trafficroutes/status
  verbs:
  - get
  - patch
  - update
