apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetraffic-controller
  labels:
    app.kubernetes.io/name: kubetraffic
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetraffic-controller
subjects:
  - kind: ServiceAccount
    name: kubetraffic-controller
    namespace: kubetraffic-system
