apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetraffic-controller
  namespace: kubetraffic-system
  labels:
    app.kubernetes.io/name: kubetraffic
    app.kubernetes.io/component: controller
