apiVersion: v1
kind: Namespace
metadata:
  name: kubetraffic-data
  labels:
    app.kubernetes.io/name: kubetraffic
    app.kubernetes.io/component: data-plane
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
